# 데이터선택

## 넘파이 실습

In [1]:
# 라이브러리 로딩 
import numpy as np

In [65]:
# 파이썬 리스트에서 넘파이로 변환 
a = [1,3.14,True,'Hello']# 리스트 
b = np.array(a)

In [66]:
# 리스트 원소 데이터 타입 확인
print(a)
for element in a:
    print('Data Type of {} : {}'.format(element, type(element)))

[1, 3.14, True, 'Hello']
Data Type of 1 : <class 'int'>
Data Type of 3.14 : <class 'float'>
Data Type of True : <class 'bool'>
Data Type of Hello : <class 'str'>


In [67]:
print(b)
for element in b:
    print('Data Type of {} : {}'.format(element, type(element)))

['1' '3.14' 'True' 'Hello']
Data Type of 1 : <class 'numpy.str_'>
Data Type of 3.14 : <class 'numpy.str_'>
Data Type of True : <class 'numpy.str_'>
Data Type of Hello : <class 'numpy.str_'>


넘파이 array 는 동일한 타입만 원소로 가질수 있기에 str 변환되어 저장됨 

In [68]:
# 중첩 리스트 생성
a =[[1,2,3],[4,5,6]]
print(a)


[[1, 2, 3], [4, 5, 6]]


In [69]:
# 중첩리스트 데이터 타입 : list
type(a)

list

In [70]:
# 중첩 리스트를 넘파이 배열로 변환 >> 2차원 행렬로 변환 
b = np.array(a)
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [71]:
# 배열의 shape 확인 
b.shape # 2 , 3 

(2, 3)

In [72]:
# 배열의 차원 확인
b.ndim

2

In [73]:
# 배열의 원소 개수 확인
b.size

6

In [74]:
#2X3 행렬을 3x2로 변화 
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [75]:
# 배열요소 데이터 타입변경 정수 >> 실수 
b = np.array(a,dtype= float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [76]:
# 배열요소 데이터 타입변경 실수 >> 정수 
b = np.array(a,dtype= int)
print(b)

[[1 2 3]
 [4 5 6]]


## 넘파이 배열 인덱싱

In [77]:
arr = np.array([1,2,3,4,5])

In [78]:
print(arr[0])

1


In [79]:
# 2차원
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1,2])

6


## 배열 슬라이싱

In [80]:
arr_2d = np.arange(1,7).reshape(2,3)
print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [81]:
print(arr_2d[0,:]) # 0번째 행만 전부 출력
print(arr_2d[:,1]) # 1번째 열만 전부 출력

[1 2 3]
[2 5]


## 판다스 

In [82]:
import pandas as pd

In [83]:
# 실습예시 딕셔너리 
data = {
    '이름': ['양정우','서길룡','남정상','이한길'],
    '학과': ['컴퓨터공학','수학','철학','경영학'],
    '성적': [4.1, 1.0 ,3.5 ,4.0]

}
data

{'이름': ['양정우', '서길룡', '남정상', '이한길'],
 '학과': ['컴퓨터공학', '수학', '철학', '경영학'],
 '성적': [4.1, 1.0, 3.5, 4.0]}

In [84]:
df = pd.DataFrame(data)
display(df)

이름     학과   성적
0  양정우  컴퓨터공학  4.1
1  서길룡     수학  1.0
2  남정상     철학  3.5
3  이한길    경영학  4.0

### 데이터 CSV 로 저장 

In [85]:
df.to_csv('./result_set/2.1데이터선택.csv', sep=',' ,index =False)

### 데이터 불러오기 

In [86]:
df = pd.read_csv('./result_set/2.1데이터선택.csv')
display(df)

이름     학과   성적
0  양정우  컴퓨터공학  4.1
1  서길룡     수학  1.0
2  남정상     철학  3.5
3  이한길    경영학  4.0

### pandas 원하는 데이터 선택하기 

### (1) 슬라이싱

In [87]:
# 데이터 슬라이싱
df[1:5] # 1~4 

이름   학과   성적
1  서길룡   수학  1.0
2  남정상   철학  3.5
3  이한길  경영학  4.0

### (2) 인덱싱

In [88]:
df[1] # key error 발생 


KeyError: 1

In [104]:
df['이름']# key값에 맞게 입력해줘야 함 

0    양정우
1    서길룡
2    남정상
3    이한길
Name: 이름, dtype: object

In [91]:
df[['이름','학과']]

이름     학과
0  양정우  컴퓨터공학
1  서길룡     수학
2  남정상     철학
3  이한길    경영학

In [92]:
# 슬라이싱 + 인덱싱 
df[1:3][['이름','학과']]

이름  학과
1  서길룡  수학
2  남정상  철학

### Boolean indexing 
(연산자를 이용하여 인덱싱 수행 )


In [94]:
df[df['학과'] =='수학'] # 조건을 만족하는 데이터만 할당 

이름  학과   성적
1  서길룡  수학  1.0

### pandas 고급 인덱싱 loc & iloc 인덱싱

In [96]:
#한개의 행에 대하서만 loc 인덱싱
df.loc[3] # index = 3 인 요소만 
type(df.loc[3])

pandas.core.series.Series

In [100]:
# 여러행 fancy 인덱싱
df.loc[[1,0,3]]


이름     학과   성적
1  서길룡     수학  1.0
0  양정우  컴퓨터공학  4.1
3  이한길    경영학  4.0

In [110]:
# 행에 대해서 fancy 인덱싱과 원하는 컬럼 인덱싱
df.loc[ [1,3,0], '이름':'학과']

이름     학과
1  서길룡     수학
3  이한길    경영학
0  양정우  컴퓨터공학

### iloc: 정수 입력
 loc는 컬럼 명을 명시 <<>> lioc 는 컬럼의 순서(정수)를 명시

In [111]:
df.iloc[[1,3,0], 0:2]

이름     학과
1  서길룡     수학
3  이한길    경영학
0  양정우  컴퓨터공학